plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ric.apolite'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ric.apolite'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging false
        }
        resources {
            excludes += ['META-INF/*']
        }
    }
}

dependencies {
}
